// <auto-generated />
using Ares.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ares.Api.Data.Migrations
{
    [DbContext(typeof(AresDbContext))]
    [Migration("20260714230819_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ares.Api.Models.CorrectiveAction", b =>
                {
                    b.Property<string>("IncidentId")
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Due")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Weak")
                        .HasColumnType("boolean");

                    b.HasKey("IncidentId", "Id");

                    b.ToTable("CorrectiveActions");
                });

            modelBuilder.Entity("Ares.Api.Models.DirectoryPrincipal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntraId")
                        .HasColumnType("text");

                    b.Property<string>("EntraSource")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Directory");
                });

            modelBuilder.Entity("Ares.Api.Models.EvidenceItem", b =>
                {
                    b.Property<string>("IncidentId")
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("T")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IncidentId", "Id");

                    b.ToTable("EvidenceItems");
                });

            modelBuilder.Entity("Ares.Api.Models.Hypothesis", b =>
                {
                    b.Property<string>("IncidentId")
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AgainstE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ForE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IncidentId", "Id");

                    b.ToTable("Hypotheses");
                });

            modelBuilder.Entity("Ares.Api.Models.Incident", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Assign")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Comms")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sel")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sev")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Started")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamsChannelId")
                        .HasColumnType("text");

                    b.Property<string>("TeamsChannelUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("Ares.Api.Models.IncidentLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IncidentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IncidentLinks");
                });

            modelBuilder.Entity("Ares.Api.Models.ReadinessDoc", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("ReadinessDocs");
                });

            modelBuilder.Entity("Ares.Api.Models.Runbook", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("LastRun")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Runbooks");
                });

            modelBuilder.Entity("Ares.Api.Models.Slo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("BudgetUsed")
                        .HasColumnType("integer");

                    b.Property<string>("Burn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Current")
                        .HasColumnType("double precision");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Target")
                        .HasColumnType("double precision");

                    b.Property<string>("Window")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Slos");
                });

            modelBuilder.Entity("Ares.Api.Models.TimelineEvent", b =>
                {
                    b.Property<string>("IncidentId")
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("T")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IncidentId", "Id");

                    b.ToTable("TimelineEvents");
                });

            modelBuilder.Entity("Ares.Api.Models.CorrectiveAction", b =>
                {
                    b.HasOne("Ares.Api.Models.Incident", "Incident")
                        .WithMany("Actions")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Ares.Api.Models.EvidenceItem", b =>
                {
                    b.HasOne("Ares.Api.Models.Incident", "Incident")
                        .WithMany("Evidence")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Ares.Api.Models.Hypothesis", b =>
                {
                    b.HasOne("Ares.Api.Models.Incident", "Incident")
                        .WithMany("Hypotheses")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Ares.Api.Models.TimelineEvent", b =>
                {
                    b.HasOne("Ares.Api.Models.Incident", "Incident")
                        .WithMany("Timeline")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Ares.Api.Models.Incident", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Evidence");

                    b.Navigation("Hypotheses");

                    b.Navigation("Timeline");
                });
#pragma warning restore 612, 618
        }
    }
}
